### ISSUE TITLE
Add pl_PL translation files

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/external-referral-links#13]
Translation provided by: https://secure.helpscout.net/conversation/657267168/89492?folderId=205529.

**Comment by amdrew** [comment]
Going to merge. Pretty sure you need to commit the language files to the WP repo initially so they are copied over. Then we can remove them after that.

@michaelbeil Going forward, all new language translations will be handled on the WP.org repo and shouldn't be submitted to GitHub as PRs. This applies only to our free add-ons. For all pro add-ons, keep submitting them as PRs.
