### ISSUE TITLE
Can't use "join" as referral variable

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/external-referral-links#7]
Much like https://github.com/AffiliateWP/AffiliateWP/issues/1589 a customer reported that when they used `join` some funky stuff happens to links when a referral link is not used.

**Comment by sumobi** [comment]
Fixed via https://github.com/AffiliateWP/external-referral-links/commit/f1c85b77c6e8dca2ae2caaa2c61abe3f41682003

**Comment by pippinsplugins** [comment]
:+1:
